### ISSUE TITLE
question about crass-assembler

### ISSUE THREAD

**Issue by ucassee** [ctSkennerton/crass#100]
Hi,
    I can't assemble the CRISPRs.
    The following is the command I used. 
    `crass -o crass_out -l 4 TS01-B10-1_1.fastq TS01-B10-1_2.fastq`
     `crass-assembler --velvet -x crass_out/crass.crispr -g 111 -s s1,s2,s3,s4,s5 -i crass_out/`
      When I run assmbler, it seemed can't find reads.
```
[root@localhost crisper]$ crass-assembler --velvet -x crass_out/crass.crispr -g 111 -s s1,s2,s3,s4,s5 -i crass_out/
velveth . 48 crass_out//crass_tmp.fa
[0.000001] Velvet can't work with even length k-mers, such as 48. We'll use 47 instead, if you don't mind.
[0.000762] Reading FastA file crass_out//crass_tmp.fa;
[0.000813] 0 sequences found
[0.000826] Done
```

But the following is the reads in  Group_111_GTGATCGATTCGTTGATGCCGAAAGGCGTTGAGCACGGAA.fa:

```
>M03609:25:000000000-AL1JM:1:1108:17032:20377 1:N:0:1
ATCGAGAGAGTGATCGATTCGTTGATGCCGAAAGGCGTTGAGCACAGAAATGAATAATTGGTCACTGCCATTTCTGTGGGTGATCGATTCGTTGATGCCGAAAGGCGTTGAGCACACGACCAACACCAGCCCGTAGAAGGCATTGATTCCGGTGATCGATTCGTTGATGCCGAAAGGCGTTGAGCACACCAACTGGCACGCCACCGCAACTGAATGTGACTCAGTGATCGATTCGTTGATGCCGAAAGGCGT
>M03609:25:000000000-AL1JM:1:1105:13678:12839 2:N:0:1
TGGCGGACTTGTGATCGATTCGTTGATGCCGAAAGGCGTTGAGCACGGGCTTGAAGATGAAGACGATTACGTGTCCCTGCCTGTGATCGATTCGTTGATGCCGAAAGGCGTTGAGCACGGAACCTGCCCGATGAATGGTGGTCAGTATTCACGACGTGATCGATTCGTTGATGCCGAAAGGCGTTGAGCACGAAA
>M03609:25:000000000-AL1JM:1:1114:10268:14844 2:N:0:1
TGGCGGACTTGTGATCGATTCGTTGATGCCGAAAGGCGTTGAGCACGGGCTTGAAGATGAAGACGATTACGTGTCCCTGCCTGTGATCGATTCGTTGATGCCGAAAGGCGTTGAGCACGGAACCTGCCAGATGAATGGTGGTCAGTCTTCACGACGGGATCGATTCGTTGATGCCGAAAGGCG
>M03609:25:000000000-AL1JM:1:2117:6920:14720 2:N:0:1
TGGCGGACTTGTGATCGATTCGTTGATGCCGAAAGGCGTTGAGCACGGGCTTGAAGATGAAGACGATTACGTGTCCCTGCCTGTGATCGATTCGTTGATGCCGAAAGGCGTTGAGCACGGAACCTGCCCGAGGAATGGTGGTCAGTATTCACGACGTGATCGATTCGTTGATGCCGAAAGGCGTTGAGCACGA
```
What should I do to debug this?  What is the meaning of -s in crass-assembler, how should I set this parameter? 
Thanks in advance.

**Comment by ctSkennerton** [comment]
I wouldn't recommend velvet anymore and `crass-assembler` hasn't been updated in a long time. You can simply take the fastq files from the groups you want, combine them manually and them put them through a newer assembler like spades.

**Comment by ucassee** [comment]
Hi @ctSkennerton,
Thanks for your reply.
If I just want to extract spacer regions after the assembling, could you give me some suggestions?

**Comment by ctSkennerton** [comment]
I think you should also have the [`crisprtools`](http://ctskennerton.github.io/crisprtools/) command. In which case you can do something like `crisprtools extract -s -g 111 file.crispr` to get the sequences of the spacers identified by crass. Alternatively you could take the reads from the group, assemble with spades (or something else) and then use [minced](https://github.com/ctSkennerton/minced) on the contigs produced.

**Comment by ucassee** [comment]
Thanks, I will try.
I have some Miseq sequencing reads (2*300). For reads longer than 200bp, is it also good to use Crass? or just use  `minced`

**Comment by ctSkennerton** [comment]
hmm, so minced treats all of the reads separately so you'll get a lot of duplications due to read depth. It also doesn't handle partial spacers/repeats that might be hanging on the edges of reads. I'd recommend crass still.

**Comment by ucassee** [comment]
Hi @ctSkennerton,
    I just want to extract all spacer sequences from metagenomes and don't need to distinguish their group. I have 40 metagenomes to deal with. If I need to extract each group in each metagenome. It is a little trivial. 
   1. Can I assemble all Group_*_*.fa files from one metagenome together? And then use ` minced`  to extract all spacers for each metagenome？Or just you  `crisprtools` to extract spacer from` crass.crispr` without assembling.
   2.From the result of `crisprtools extract -s crass.crispr > all.spacer`, I find some spacers are shorter than 20bp. Is it a positive result (attached below)? 
```
>G12SP5_Cov_1
GTCCAACACCACAGGAAGTG
>G12SP8_Cov_1
ATATCAACACCACGGGCAGCT
>G12SP24_Cov_1
TTTCCAACACCGCGGGTAGCA
```

**Comment by ctSkennerton** [comment]
1. You could assemble them all together but I don't know how that will affect the assembler output. I'd try both ways to see the difference.
2. I believe that is because crass will also identify partial spacers towards the end of the reads. It's also possible that this is a bug in the software. It's been so long since I wrote this code that I don't remember all the details
3. Sure, why not, it's a good comparison point.

**Comment by ucassee** [comment]
Hi,
I find some spacers longer than 100bp by crass with metagenomic reads, are these positive result?

```
spacer cov="4" seq="AAATGGGTATTGCCTTTTTATAGAGAGTAAAAAGGCAAAGCACTAGGAATAAGATATGAAGTACATGTGCAGAACCTGTAAAAAAAAATGTGATGATATTCTAGAACATTTGATGACAGTAC" spid="SP3890"
spacer cov="1" seq="AAATGTGTATTGCCTTTTTATAGAGAGTAAAAAGGCAAAGCACTAGGAATAAGATATGAAGTACATGTGCAGAACCTGTAAAAAAAAATGTGATGATATTCTAAAACATTTGATGACAGTA" spid="SP11579"
```

**Comment by ctSkennerton** [comment]
Probably not, they seem too long.
