### ISSUE TITLE
FATAL ERROR: parseSeqFiles failed

### ISSUE THREAD

**Issue by maureenbug** [ctSkennerton/crass#101]
Hi! I saw that people previously had this issue back in 2016, but this error recently came up for me. I only get this error on certain datasets, so I'm not sure if there is something wrong with them (and something I can check)? 

here is the version information:
`CRisprASSembler (crass)
version 0 subversion 3 revison 12 (0.3.12)`

here is the tail end of the log file

`>A00178:49:H7L3HDSXX:2:2678:25129:8656 1:N:0:TCGTGGAT+ATCCACGA
GTTTCACACCGGACGAAGAACACGTCGCGTTTGTCGAGAAATACCGAAACTTTGTAATCCCCTGGCGGGGATTTAGGTGTTTCACACATATCTGCGCGGTATGATAGAGACACAGTAATCGATCTTTGTAATCCCCTGGCGGGGATTTAGG
3d 8h 21m 24s	ERR WorkHorse.cpp : int WorkHorse::doWork(Vecstr) : 191: FATAL ERROR: parseSeqFiles failed`

CRASS will always fail and give this error (on this dataset) at the same sequence. I did try running CRASS just on  "A00178:49:H7L3HDSXX:2:2678:25129:8656" the last sequence listed, but it runs fine.

Any help is appreciated thanks!

**Comment by ctSkennerton** [comment]
Can you update to the latest version to see if that fixes it?

**Comment by ctSkennerton** [comment]
is the dataset public or something that I could access to see if I can reproduce?

**Comment by maureenbug** [comment]
it is!

https://img.jgi.doe.gov/cgi-bin/mer/main.cgi?section=TaxonDetail&page=taxonDetail&taxon_oid=3300031980

you can download here: https://data.jgi.doe.gov/refine-download/img?its_ap_id=1209422&expanded=1209422

**Comment by ctSkennerton** [comment]
is there any smaller datasets? I don't have access to a server anymore to do personal projects and the files are too big to process on my laptop.

**Comment by maureenbug** [comment]
let me try to split up the data into subsets and see if I still get the same error on those subsets - then I can send one of those to you

**Comment by maureenbug** [comment]
okay I ran CRASS on the subsets of data to see which one to send you, but they all worked??? so I guess everything is good now?

**Comment by ctSkennerton** [comment]
yeah, bug was probably caused during the graph construction which is dependent on input file. But the reads that get identified at the beginning shouldn't change too much.
