### ISSUE TITLE
Substring error

### ISSUE THREAD

**Issue by ctSkennerton** [ctSkennerton/crass#61]
When processing M90809 dataset, obtained the following error message:
```
[crass_clusterCore]: 59178 non-redundant patterns.
[crass_singletonFinder]: Processed 253461380 ...296617 sec
[crass_patternFinder]: Found 1085779 reads
[crass_graphBuilder]: 3929 putative CRISPRs found!
[SUBSTRING_ERROR]: basic_string::substr
ReadHolder.cpp : 878 : bool ReadHolder::getNextSpacer(std::string*)
Cutting substr: -4 : 154
From Read: CGCCCGCGCTGGGGCCGGTCTCCTGACCGAGCCCCGCCCCGCCCGCCCCGGGGGGGGGGCCCTTCCCCCCGGCCGCCCCCGCCCCCGCCCCGGCCACACCGCCCCCCCCCCACCACGCTTCCTCCGCCCCCCCGCCCCGCGCCCGCCCCT
Length: 150

[ERROR]: Failed to get first spacer
ReadHolder.cpp : 818 : bool ReadHolder::getFirstSpacer(std::string*)
```

**Comment by michberr** [comment]
I just received a similar error. I'm using CRASS V 0.3.12

[crass_patternFinder]: Processed 20000000 ...262 sec
[crass_clusterCore]: 58120 variants mapped to 32534 clusters
[crass_clusterCore]: creating non-redundant set
[crass_clusterCore]: 96300 non-redundant patterns.
[crass_singletonFinder]: Processed 20000000 ...13428 sec
[crass_patternFinder]: Found 433289 reads
185 : 219
[ERROR]: Something wrong with front offset!
ss iter: 102
front offset: -34
Header: HWI-D00196:168:C66U5ANXX:3:2302:10815:3937
LowLexi: 1 
 34,76,102,100,
Sequence:ATTCGGATCCGTATCAAATTTAAGTAGATAACAACAGTGTTGCGGATCCGGGATATTTTCTATCATGGATTCGGATCCGTATCAAATTTAAGTAGATAACA
Len: 101

**Comment by ctSkennerton** [comment]
Hi Michelle,

crass doesn't crass for me when I use just this read which means that there is something funky happening with the full dataset that is causing this to occur or there is a difference in the settings that is causing this. Are you running it with any non-default settings? Is it possible to send me the dataset (or a subset of it that still causes a crash) so that I can debug it?

**Comment by michberr** [comment]
Hi Connor, thanks for your quick reply! 

I ran CRASS with default settings. When I run crass on just that sequence I don't get an error either. Unfortunately today i cannot replicate the error (despite running 3 times yesterday with the same error). Must be an environment thing. I'll post back if i encounter this error again. 

Best,
Michelle
