### ISSUE TITLE
new segmentation fault error

### ISSUE THREAD

**Issue by seano30** [ctSkennerton/crass#70]
I am getting a segmentation fault error when I run Crass v0.3.9 with no other parameters toggled for input. Interestingly, I was not receiving this error when running this file and v0.3.7 of Crass. And more interestingly, a file that was giving me a segmentation fault error using v0.3.7 of Crass is no longer giving me an error with v0.3.9. I am happy to provide a log file if that is desired. Also FYI, I am using two HISEQ fastq files as input.

**Comment by ctSkennerton** [comment]
I fix one thing and it causes something else :tired_face:. Please post the log file, or send it to me via   email (c.skennerton@gmail.com). Are the files that your running it on very large? is there some smaller subset of the data that is also creating the error, which you could send to me as well?
