### ISSUE TITLE
crass make failure

### ISSUE THREAD

**Issue by chriswalls** [ctSkennerton/crass#71]
I'm attempting to install crass-0.3.10 on our Centos cluster. I believe I have all the the necessary programs (and correct versions) installed including xercesc (from my distribution) and libcrispr (/usr/local/ctSkennerton-libcrispr-9efca1a). They are installed in the expected locations and are found when I run ./configure. When I run the make (or make install), I get a lot of undefined references. I'll just put one here and then the make error statements:

/usr/local/bin/crass-0.3.10/src/crass/WorkHorse.cpp:1988: undefined reference to `crispr::xml::writer::addAssembly(xercesc_3_1::DOMElement*)'
collect2: ld returned 1 exit status
make[3]: *** [crass] Error 1
make[3]: Leaving directory `/usr/local/bin/crass-0.3.10/src/crass'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/usr/local/bin/crass-0.3.10/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/usr/local/bin/crass-0.3.10'
make: *** [all] Error 2

I've poured over other people's issues but have found no solution. Can you give me any guidance?

**Comment by ctSkennerton** [comment]
I think that the issue is that libcrispr isn't being found by the compiler. To fix this up you need to update your `LD_LIBRARY_PATH` environmental variable. You can update your environment in bash by typing:
```
export LD_LIBRARY_PATH=/usr/local/ctSkennerton-libcrispr-9efca1a/lib:$LD_LIBRARY_PATH
```
(note to make this change permanent you will need to add this line to your bashrc)

Then when running `configure` add the `--with-libcrispr` option like so:
```
./configure --with-libcrispr=/usr/local/ctSkennerton-libcrispr-9efca1a
```
and hopefully it will work

**Comment by chriswalls** [comment]
Thank you for the reply.

I had tried the --with-libcrispr option but not the environmental variable. I just tried both and I am getting the same result. 

IDK if it's helpful, but I had tried installing xercesc compiling binary (after an earlier failed attempt from distribution). That always resulted in cannot find libcrispr  at the compile step. Just now when the environmental variable and --with-libcrispr also failed, I also tried adding --with-xercesc=/user/local/include/xercesc. That time I got a cannot find libcrispr  error. (Where does it look for xercesc by default?)

**Comment by ctSkennerton** [comment]
Okay, two questions:
what commands did you type in to get libcrispr installed? 
what is the contents of the `/usr/local/ctSkennerton-libcrispr-9efca1a` directory?

**Comment by chriswalls** [comment]
Sorry,  the delay in my reply was due to a family emergency. My answers are below.

To install:
tar xf ctSkennerton-libcrispr-1.0.1-0-g9efca1a.tar.gz
cd ctSkennerton-libcrispr-9efca1a
sudo ./autogen.sh
sudo ./configure
sudo make install

$ ls /usr/local/ctSkennerton-libcrispr-9efca1a
aclocal.m4  autom4te.cache  config.h     config.h.in~  config.status  configure.ac  libcrispr  m4        Makefile.am  README.md autogen.sh  build           config.h.in  config.log    configure      doc           libtool    Makefile  Makefile.in  stamp-h1

**Comment by ctSkennerton** [comment]
Alright, libcrispr is not installed where I thought it was. Your `sudo make install` command is going to put it in the default location for your system, which will probably be `/usr/local/lib`. Can you confirm this by `ls` that directory, hopefully you'll see libcrispr.

If you do see it then try out:
```
export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
./configure --with-libcrispr=/usr/local/
```

**Comment by chriswalls** [comment]
Thanks. Unfortunately, I'm still getting the Workhorse undefined reference & make errors.

**Comment by ctSkennerton** [comment]
Ah, you mean those files were in /usr/local/**lib**, right?

If so, then that seems correct to me, and since there were no errors when you installed libcrispr, xercesc should be in the right place as well. Very confusing. Sometimes after a few failed compilations things can get out of whack, try running `make clean` and then running `make` again. If that doesn't work then please send me the full terminal output and maybe I can gleam something from that

**Comment by chriswalls** [comment]
Here’s my output. I really appreciate you taking a look at it!
Chris

**Comment by ctSkennerton** [comment]
I don't know what's going on but I'm going to modify the code such that there is no need for a separate libcrispr installation. That way everything will just be easier to install cause the only dependency will be xerces. It will take me a day or so and then I'll make a new version and, fingers-crossed it will work.

**Comment by chriswalls** [comment]
That sounds wonderful!


Sent from my Verizon Wireless 4G LTE smartphone


-------- Original message --------

**Comment by ctSkennerton** [comment]
I've just put up a new version of crass onto github, v0.3.11, which has an easier installation process. With just Xerces on your system it should now compile.

**Comment by ctSkennerton** [comment]
actually don't use v0.3.11, use v0.3.12 instead

**Comment by chriswalls** [comment]
Thank you! I'm out of town but will try it out as soon as I get back on Monday.
Chris


Sent from my Verizon Wireless 4G LTE smartphone


-------- Original message --------

**Comment by chriswalls** [comment]
Just installed the new version. No problems! Thanks sooo much!!!
