### ISSUE TITLE
Crass make failure #'Utils.h' file not found

### ISSUE THREAD

**Issue by fmoyaflores** [ctSkennerton/crass#72]
Hi ctSkennerton,

I've been trying to install crass on my computer during the past days, and I came across some posts in github with the same issues I've been dealing with. I've tested the newest version of the software (v0.3.11) just now. I see some things working this time (the libcrispr error doesn't appear anymore), but I'm still unable to get it to work. Here's the log info, with the errors appearing at the end:

dyn-72-33-149-176:crass-0.3.11 Francisco$ ./autogen.sh
Preparing the crass build system...please wait

Found GNU Autoconf version 2.69
Found GNU Automake version 1.15
Found GNU Libtool version 2.4

Automatically preparing build ... done

The crass build system is now prepared.  To build here, run:
  ./configure
  make

dyn-72-33-149-176:crass-0.3.11 Francisco$ sudo ./configure 
Password:
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... build/install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... x86_64-apple-darwin14.1.0
checking host system type... x86_64-apple-darwin14.1.0
checking how to print strings... printf
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /Library/Developer/CommandLineTools/usr/bin/ld
checking if the linker (/Library/Developer/CommandLineTools/usr/bin/ld) is GNU ld... no
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm
checking the name lister (/usr/bin/nm) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 196608
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-apple-darwin14.1.0 file names to x86_64-apple-darwin14.1.0 format... func_convert_file_noop
checking how to convert x86_64-apple-darwin14.1.0 file names to toolchain format... func_convert_file_noop
checking for /Library/Developer/CommandLineTools/usr/bin/ld option to reload object files... -r
checking for objdump... no
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... no
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm output from gcc object... ok
checking for sysroot... no
checking for mt... no
checking if : is a manifest tool... no
checking for dsymutil... dsymutil
checking for nmedit... nmedit
checking for lipo... lipo
checking for otool... otool
checking for otool64... no
checking for -single_module linker flag... yes
checking for -exported_symbols_list linker flag... yes
checking for -force_load linker flag... yes
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... yes
checking for gcc option to produce PIC... -fno-common -DPIC
checking if gcc PIC flag -fno-common -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin14.1.0 dyld
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /Library/Developer/CommandLineTools/usr/bin/ld
checking if the linker (/Library/Developer/CommandLineTools/usr/bin/ld) is GNU ld... no
checking whether the g++ linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... yes
checking for g++ option to produce PIC... -fno-common -DPIC
checking if g++ PIC flag -fno-common -DPIC works... yes
checking if g++ static flag -static works... no
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin14.1.0 dyld
checking how to hardcode library paths into programs... immediate
checking whether we are using the GNU C++ compiler... (cached) yes
checking whether g++ accepts -g... (cached) yes
checking dependency style of g++... (cached) gcc3
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... -D_THREAD_SAFE
checking for PTHREAD_PRIO_INHERIT... yes
checking for Xerces C++ Parser headers in /usr/local/include and /usr/local/include/xercesc... found
checking for Xerces C++ Parser libraries... found
checking for Xerces C++ Parser... yes
checking for velvetg... no
checking for cap3... no
checking for gzread in -lz... yes
checking for ANSI C header files... (cached) yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for unistd.h... (cached) yes
checking getopt.h usability... yes
checking getopt.h presence... yes
checking for getopt.h... yes
checking for stdbool.h that conforms to C99... yes
checking for _Bool... yes
checking for an ANSI C-conforming const... yes
checking for inline... inline
checking for size_t... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible realloc... yes
checking for memset... yes
checking for pow... yes
checking for strchr... yes
checking for strspn... yes
checking for pdflatex... no
configure: WARNING: Unable to create PDF version of the user manual.
checking for cap3... no
checking for velvetg... no
checking for velveth... no
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating src/crass/Makefile
config.status: creating man/Makefile
config.status: creating doc/Makefile
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands

dyn-72-33-149-176:crass-0.3.11 Francisco$ sudo make
Password:
/Library/Developer/CommandLineTools/usr/bin/make  all-recursive
Making all in src
Making all in crass
g++ -DHAVE_CONFIG_H -I. -I../..    -I/usr/local/include -I/usr/local/include/xercesc -pedantic -Wall -g -O2 -MT PatternMatcher.o -MD -MP -MF .deps/PatternMatcher.Tpo -c -o PatternMatcher.o PatternMatcher.cpp
mv -f .deps/PatternMatcher.Tpo .deps/PatternMatcher.Po
g++ -DHAVE_CONFIG_H -I. -I../..    -I/usr/local/include -I/usr/local/include/xercesc -pedantic -Wall -g -O2 -MT Rainbow.o -MD -MP -MF .deps/Rainbow.Tpo -c -o Rainbow.o Rainbow.cpp
mv -f .deps/Rainbow.Tpo .deps/Rainbow.Po
g++ -DHAVE_CONFIG_H -I. -I../..    -I/usr/local/include -I/usr/local/include/xercesc -pedantic -Wall -g -O2 -MT crass.o -MD -MP -MF .deps/crass.Tpo -c -o crass.o crass.cpp
In file included from crass.cpp:53:
In file included from ./crass.h:47:
./kseq.h:76:7: warning: no newline at end of file [-Wnewline-eof]
#endif
      ^
In file included from crass.cpp:53:
In file included from ./crass.h:49:
In file included from ./WorkHorse.h:50:
In file included from ./NodeManager.h:61:
In file included from ./writer.h:37:
./base.h:412:8: warning: no newline at end of file [-Wnewline-eof]
#endif 
       ^
In file included from crass.cpp:53:
In file included from ./crass.h:49:
In file included from ./WorkHorse.h:50:
In file included from ./NodeManager.h:61:
./writer.h:275:7: warning: no newline at end of file [-Wnewline-eof]
#endif
      ^
In file included from crass.cpp:53:
In file included from ./crass.h:49:
In file included from ./WorkHorse.h:58:
In file included from ./Aligner.h:42:
./ksw.h:72:7: warning: no newline at end of file [-Wnewline-eof]
#endif
      ^
4 warnings generated.
mv -f .deps/crass.Tpo .deps/crass.Po
g++ -DHAVE_CONFIG_H -I. -I../..    -I/usr/local/include -I/usr/local/include/xercesc -pedantic -Wall -g -O2 -MT WuManber.o -MD -MP -MF .deps/WuManber.Tpo -c -o WuManber.o WuManber.cpp
mv -f .deps/WuManber.Tpo .deps/WuManber.Po
g++ -DHAVE_CONFIG_H -I. -I../..    -I/usr/local/include -I/usr/local/include/xercesc -pedantic -Wall -g -O2 -MT LoggerSimp.o -MD -MP -MF .deps/LoggerSimp.Tpo -c -o LoggerSimp.o LoggerSimp.cpp
mv -f .deps/LoggerSimp.Tpo .deps/LoggerSimp.Po
g++ -DHAVE_CONFIG_H -I. -I../..    -I/usr/local/include -I/usr/local/include/xercesc -pedantic -Wall -g -O2 -MT SeqUtils.o -MD -MP -MF .deps/SeqUtils.Tpo -c -o SeqUtils.o SeqUtils.cpp
mv -f .deps/SeqUtils.Tpo .deps/SeqUtils.Po
g++ -DHAVE_CONFIG_H -I. -I../..    -I/usr/local/include -I/usr/local/include/xercesc -pedantic -Wall -g -O2 -MT CrisprNode.o -MD -MP -MF .deps/CrisprNode.Tpo -c -o CrisprNode.o CrisprNode.cpp
In file included from CrisprNode.cpp:44:
In file included from ./CrisprNode.h:50:
In file included from ./libcrispr.h:53:
./kseq.h:76:7: warning: no newline at end of file [-Wnewline-eof]
#endif
      ^
1 warning generated.
mv -f .deps/CrisprNode.Tpo .deps/CrisprNode.Po
g++ -DHAVE_CONFIG_H -I. -I../..    -I/usr/local/include -I/usr/local/include/xercesc -pedantic -Wall -g -O2 -MT NodeManager.o -MD -MP -MF .deps/NodeManager.Tpo -c -o NodeManager.o NodeManager.cpp
In file included from NodeManager.cpp:48:
In file included from ./NodeManager.h:54:
In file included from ./CrisprNode.h:50:
In file included from ./libcrispr.h:53:
./kseq.h:76:7: warning: no newline at end of file [-Wnewline-eof]
#endif
      ^
In file included from NodeManager.cpp:48:
In file included from ./NodeManager.h:61:
In file included from ./writer.h:37:
./base.h:412:8: warning: no newline at end of file [-Wnewline-eof]
#endif 
       ^
In file included from NodeManager.cpp:48:
In file included from ./NodeManager.h:61:
./writer.h:275:7: warning: no newline at end of file [-Wnewline-eof]
#endif
      ^
3 warnings generated.
mv -f .deps/NodeManager.Tpo .deps/NodeManager.Po
g++ -DHAVE_CONFIG_H -I. -I../..    -I/usr/local/include -I/usr/local/include/xercesc -pedantic -Wall -g -O2 -MT libcrispr.o -MD -MP -MF .deps/libcrispr.Tpo -c -o libcrispr.o libcrispr.cpp
In file included from libcrispr.cpp:54:
In file included from ./libcrispr.h:53:
./kseq.h:76:7: warning: no newline at end of file [-Wnewline-eof]
#endif
      ^
1 warning generated.
mv -f .deps/libcrispr.Tpo .deps/libcrispr.Po
g++ -DHAVE_CONFIG_H -I. -I../..    -I/usr/local/include -I/usr/local/include/xercesc -pedantic -Wall -g -O2 -MT WorkHorse.o -MD -MP -MF .deps/WorkHorse.Tpo -c -o WorkHorse.o WorkHorse.cpp
In file included from WorkHorse.cpp:55:
In file included from ./WorkHorse.h:49:
In file included from ./libcrispr.h:53:
./kseq.h:76:7: warning: no newline at end of file [-Wnewline-eof]
#endif
      ^
In file included from WorkHorse.cpp:55:
In file included from ./WorkHorse.h:50:
In file included from ./NodeManager.h:61:
In file included from ./writer.h:37:
./base.h:412:8: warning: no newline at end of file [-Wnewline-eof]
#endif 
       ^
In file included from WorkHorse.cpp:55:
In file included from ./WorkHorse.h:50:
In file included from ./NodeManager.h:61:
./writer.h:275:7: warning: no newline at end of file [-Wnewline-eof]
#endif
      ^
In file included from WorkHorse.cpp:55:
In file included from ./WorkHorse.h:58:
In file included from ./Aligner.h:42:
./ksw.h:72:7: warning: no newline at end of file [-Wnewline-eof]
#endif
      ^
4 warnings generated.
mv -f .deps/WorkHorse.Tpo .deps/WorkHorse.Po
g++ -DHAVE_CONFIG_H -I. -I../..    -I/usr/local/include -I/usr/local/include/xercesc -pedantic -Wall -g -O2 -MT SpacerInstance.o -MD -MP -MF .deps/SpacerInstance.Tpo -c -o SpacerInstance.o SpacerInstance.cpp
In file included from SpacerInstance.cpp:41:
In file included from ./SpacerInstance.h:48:
In file included from ./CrisprNode.h:50:
In file included from ./libcrispr.h:53:
./kseq.h:76:7: warning: no newline at end of file [-Wnewline-eof]
#endif
      ^
1 warning generated.
mv -f .deps/SpacerInstance.Tpo .deps/SpacerInstance.Po
g++ -DHAVE_CONFIG_H -I. -I../..    -I/usr/local/include -I/usr/local/include/xercesc -pedantic -Wall -g -O2 -MT ReadHolder.o -MD -MP -MF .deps/ReadHolder.Tpo -c -o ReadHolder.o ReadHolder.cpp
mv -f .deps/ReadHolder.Tpo .deps/ReadHolder.Po
g++ -DHAVE_CONFIG_H -I. -I../..    -I/usr/local/include -I/usr/local/include/xercesc -pedantic -Wall -g -O2 -MT SmithWaterman.o -MD -MP -MF .deps/SmithWaterman.Tpo -c -o SmithWaterman.o SmithWaterman.cpp
mv -f .deps/SmithWaterman.Tpo .deps/SmithWaterman.Po
g++ -DHAVE_CONFIG_H -I. -I../..    -I/usr/local/include -I/usr/local/include/xercesc -pedantic -Wall -g -O2 -MT StringCheck.o -MD -MP -MF .deps/StringCheck.Tpo -c -o StringCheck.o StringCheck.cpp
mv -f .deps/StringCheck.Tpo .deps/StringCheck.Po
g++ -DHAVE_CONFIG_H -I. -I../..    -I/usr/local/include -I/usr/local/include/xercesc -pedantic -Wall -g -O2 -MT kseq.o -MD -MP -MF .deps/kseq.Tpo -c -o kseq.o kseq.cpp
In file included from kseq.cpp:36:
./kseq.h:76:7: warning: no newline at end of file [-Wnewline-eof]
#endif
      ^
kseq.cpp:226:2: warning: no newline at end of file [-Wnewline-eof]
}
 ^
2 warnings generated.
mv -f .deps/kseq.Tpo .deps/kseq.Po
g++ -DHAVE_CONFIG_H -I. -I../..    -I/usr/local/include -I/usr/local/include/xercesc -pedantic -Wall -g -O2 -MT SearchChecker.o -MD -MP -MF .deps/SearchChecker.Tpo -c -o SearchChecker.o SearchChecker.cpp
SearchChecker.cpp:65:2: warning: no newline at end of file [-Wnewline-eof]
}
 ^
1 warning generated.
mv -f .deps/SearchChecker.Tpo .deps/SearchChecker.Po
gcc -DHAVE_CONFIG_H -I. -I../..     -g -O2 -MT ksw.o -MD -MP -MF .deps/ksw.Tpo -c -o ksw.o ksw.c
mv -f .deps/ksw.Tpo .deps/ksw.Po
g++ -DHAVE_CONFIG_H -I. -I../..    -I/usr/local/include -I/usr/local/include/xercesc -pedantic -Wall -g -O2 -MT Aligner.o -MD -MP -MF .deps/Aligner.Tpo -c -o Aligner.o Aligner.cpp
In file included from Aligner.cpp:37:
In file included from ./Aligner.h:42:
./ksw.h:72:7: warning: no newline at end of file [-Wnewline-eof]
#endif
      ^
1 warning generated.
mv -f .deps/Aligner.Tpo .deps/Aligner.Po
g++ -DHAVE_CONFIG_H -I. -I../..    -I/usr/local/include -I/usr/local/include/xercesc -pedantic -Wall -g -O2 -MT base.o -MD -MP -MF .deps/base.Tpo -c -o base.o base.cpp
In file included from base.cpp:35:
./base.h:412:8: warning: no newline at end of file [-Wnewline-eof]
#endif 
       ^
1 warning generated.
mv -f .deps/base.Tpo .deps/base.Po
g++ -DHAVE_CONFIG_H -I. -I../..    -I/usr/local/include -I/usr/local/include/xercesc -pedantic -Wall -g -O2 -MT parser.o -MD -MP -MF .deps/parser.Tpo -c -o parser.o parser.cpp
In file included from parser.cpp:35:
In file included from ./parser.h:37:
In file included from ./reader.h:37:
./base.h:412:8: warning: no newline at end of file [-Wnewline-eof]
#endif 
       ^
In file included from parser.cpp:35:
In file included from ./parser.h:37:
./reader.h:63:7: warning: no newline at end of file [-Wnewline-eof]
#endif
      ^
In file included from parser.cpp:35:
In file included from ./parser.h:38:
./writer.h:275:7: warning: no newline at end of file [-Wnewline-eof]
#endif
      ^
In file included from parser.cpp:35:
./parser.h:50:7: warning: no newline at end of file [-Wnewline-eof]
#endif
      ^
parser.cpp:40:3: warning: no newline at end of file [-Wnewline-eof]
{}
  ^
5 warnings generated.
mv -f .deps/parser.Tpo .deps/parser.Po
g++ -DHAVE_CONFIG_H -I. -I../..    -I/usr/local/include -I/usr/local/include/xercesc -pedantic -Wall -g -O2 -MT reader.o -MD -MP -MF .deps/reader.Tpo -c -o reader.o reader.cpp
In file included from reader.cpp:35:
In file included from ./reader.h:37:
./base.h:412:8: warning: no newline at end of file [-Wnewline-eof]
#endif 
       ^
In file included from reader.cpp:35:
./reader.h:63:7: warning: no newline at end of file [-Wnewline-eof]
#endif
      ^
2 warnings generated.
mv -f .deps/reader.Tpo .deps/reader.Po
g++ -DHAVE_CONFIG_H -I. -I../..    -I/usr/local/include -I/usr/local/include/xercesc -pedantic -Wall -g -O2 -MT writer.o -MD -MP -MF .deps/writer.Tpo -c -o writer.o writer.cpp
In file included from writer.cpp:35:
In file included from ./writer.h:37:
./base.h:412:8: warning: no newline at end of file [-Wnewline-eof]
#endif 
       ^
In file included from writer.cpp:35:
./writer.h:275:7: warning: no newline at end of file [-Wnewline-eof]
#endif
      ^
./writer.h:45:17: warning: private field 'XW_CurrentSourceId' is not used [-Wunused-private-field]
            int XW_CurrentSourceId;
                ^
3 warnings generated.
mv -f .deps/writer.Tpo .deps/writer.Po
/bin/sh ../../libtool  --tag=CXX   --mode=link g++ -I/usr/local/include -I/usr/local/include/xercesc -pedantic -Wall -g -O2 -L/usr/local/lib  -lz -lxerces-c   -o crass PatternMatcher.o Rainbow.o crass.o WuManber.o LoggerSimp.o SeqUtils.o CrisprNode.o NodeManager.o libcrispr.o WorkHorse.o SpacerInstance.o ReadHolder.o SmithWaterman.o StringCheck.o kseq.o SearchChecker.o ksw.o Aligner.o base.o parser.o reader.o writer.o  
libtool: link: g++ -I/usr/local/include -I/usr/local/include/xercesc -pedantic -Wall -g -O2 -o crass PatternMatcher.o Rainbow.o crass.o WuManber.o LoggerSimp.o SeqUtils.o CrisprNode.o NodeManager.o libcrispr.o WorkHorse.o SpacerInstance.o ReadHolder.o SmithWaterman.o StringCheck.o kseq.o SearchChecker.o ksw.o Aligner.o base.o parser.o reader.o writer.o -Wl,-bind_at_load  -L/usr/local/lib -lz -lxerces-c
g++ -DHAVE_CONFIG_H -I. -I../..    -I/usr/local/include -I/usr/local/include/xercesc -pedantic -Wall -g -O2 -MT crisprtools.o -MD -MP -MF .deps/crisprtools.Tpo -c -o crisprtools.o crisprtools.cpp
crisprtools.cpp:25:10: fatal error: 'Utils.h' file not found
#include "Utils.h"
         ^
1 error generated.
make[3]: *** [crisprtools.o] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

I also tried sudo ./configure --with-xerces=/usr/local/opt/xerces-c with the same results.
I hope you can help me solve this issue.

Thanks!
Francisco

**Comment by ctSkennerton** [comment]
Oops, forgot to add in a file to that latest release. Try now with v0.3.12

**Comment by fmoyaflores** [comment]
Yes it worked! Thanks!
