### ISSUE TITLE
counter overflows when there is too much deluge

### ISSUE THREAD

**Issue by wwood** [ctSkennerton/crass#73]
Welcome to the future

```
<snip>
[crass_patternFinder]: Processed 2147185588 ...105570 sec
[crass_patternFinder]: Processed 2147285588 ...105576 sec
[crass_patternFinder]: Processed 2147385588 ...105582 sec
[crass_patternFinder]: Processed -2147481708 ...105588 sec
[crass_patternFinder]: Processed -2147381708 ...105594 sec
[crass_patternFinder]: Processed -2147281708 ...105599 sec
<snip>
[crass_patternFinder]: Processed -719248626 ...172908 sec
```

It hasn't finished patternFinder yet, but will this cause problems in the next step?

Perhaps I am abusing more than using crass here? I'm throwing data at it from a number of metagenomes.

**Comment by ctSkennerton** [comment]
Well that's just the counter for the logging hitting an integer overflow, which in itself shouldn't cause a problem. However, if it's taking this long then it's going to be running for a long time on the next step. If your running through many different samples at once you may be better off doing them separately, of course your going to loose coverage which may make you miss stuff.

**Comment by wwood** [comment]
OK, thanks. I'm doing that too but thought I may as well go crazy. Only 1
cpu and very minimal memory taken (so far).

On 11 April 2015 at 17:15, Connor T. Skennerton <notifications@github.com>
wrote:

> Well that's just the counter for the logging hitting an integer overflow,
> which in itself shouldn't cause a problem. However, if it's taking this
> long then it's going to be running for a long time on the next step. If
> your running through many different samples at once you may be better off
> doing them separately, of course your going to loose coverage which may
> make you miss stuff.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ctSkennerton/crass/issues/73#issuecomment-91782126>.
>



-- 
--
Ben Woodcroft
http://ecogenomic.org/users/ben-woodcroft <http://www.ecogenomic.org/>
