### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by shaman-narayanasamy** [ctSkennerton/crass#74]
Hi,

I am trying to install crass. I have all the necessary dependencies and the `./autogen` step works.

However, it fails when I try to configure...
```
 $ ./configure 
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
./configure: line 2966: LT_INIT: command not found
./configure: line 2967: syntax error near unexpected token `C++'
./configure: line 2967: `LT_LANG(C++)'
```

Any idea what is going on?

Best,
Shaman

**Comment by ctSkennerton** [comment]
`LT_INIT` is the libtool initialization command, if if is not found then there must be something wrong with that. Is libtool installed and what version do you have?

**Comment by shaman-narayanasamy** [comment]
Thanks for the speedy reply. The libtool version is: 1.4.3

**Comment by ctSkennerton** [comment]
You need version 2.2 or higher. Check the [manual](http://bioinformatics.ninja/crass/assets/manual.pdf) section 2.1 to make sure that you have the other version requirements met.

**Comment by shaman-narayanasamy** [comment]
I tried again with a higher version of libtool, but obtained the same error:

```
# ./autogen.sh
Preparing the crass build system...please wait

Found GNU Autoconf version 2.69
Found GNU Automake version 1.14.1
Found GNU Libtool version 2.4

Automatically preparing build ... done

The crass build system is now prepared.  To build here, run:
  ./configure
  make
root@d51de799f0b6:/home/imp/lib/crass# ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
./configure: line 2966: LT_INIT: command not found
./configure: line 2967: syntax error near unexpected token `C++'
./configure: line 2967: `LT_LANG(C++)'
```

**Comment by ctSkennerton** [comment]
Well that is strange, the only thing that I've found through google is when libtool isn't installed correctly. What kind of system are you running? what OS, version etc. ? how did you install the new version of libtool?

**Comment by shaman-narayanasamy** [comment]
Actually, I am trying to run it within a `docker` container. The following is my OS:
```
# cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.3 LTS"
NAME="Ubuntu"
VERSION="14.04.3 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.3 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
```

Here is my installation for `libtools`:
```wget ftp://ftp.gnu.org/gnu/libtool/libtool-2.4.tar.gz
tar zxvf libtool-2.4.tar.gz
cd libtool-2.4

./configure
make
make install
```

Installation seems to run with no issues. The OS is  lightweight, meaning it is very minimal. Maybe there is some underlying dependency I am missing...

**Comment by shaman-narayanasamy** [comment]
Looks like this solved it:
```
sudo apt-get update
sudo apt-get install libtool
```

Seems like I was looking in the wrong place. Sorry for the trouble.
