### ISSUE TITLE
Crass throwing an instance of 'std::out_of_range'

### ISSUE THREAD

**Issue by rwolfe45** [ctSkennerton/crass#75]
Hi,

I have been running crass on a fasta file of 7,320,521 reads and I am getting the following error:

terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check
Aborted

This is the full output to the screen:
[crass_patternFinder]: Processed 7320521 ...131 sec
[crass_clusterCore]: 3174 variants mapped to 1532 clusters
[crass_clusterCore]: creating non-redundant set
[crass_clusterCore]: 5252 non-redundant patterns.
[crass_singletonFinder]: Processed 7320521 ...363 sec
[crass_patternFinder]: Found 20915 reads
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check
Aborted

Also, I notice that crass is only running on 1 of my 80 processors. Is there a way to parallelize crass?

**Comment by ctSkennerton** [comment]
Hi,

Is this data publicly available or is it possible for you to send me the file you used as input so that I can debug this? There also isn't a way to parallelize crass; sadly I'm not a good enough programmer to figure that sort of thing out.

**Comment by rwolfe45** [comment]
Conner,

Thanks for your quick response. When I split this file in half it runs okay on each half.

I put the file onto drop box and here is the link:
https://www.dropbox.com/s/mgs6yyog00h13tn/halfaa.fasta?dl=0


Our lab likes crass and we use it  a lot. Because we use some very large data sets, I will try to parallelize it and let you know if I am successful.

Thanks
Rich Wolfe
________________________________

**Comment by ctSkennerton** [comment]
Hi Rich,

I just tried on my computer and your file worked fine. What version of Crass are you using, what operating system and what compiler and version did you use to make the software?

**Comment by rwolfe45** [comment]
Connor,

Version:
CRisprASSembler (crass)
version 0 subversion 3 revison 7 (0.3.8)

OS: x86_64-redhat-linux

gcc -v : gcc version 4.4.7 20120313 (Red Hat 4.4.7-16) (GCC)

I just installed version 0 subversion 3 revison 12 (0.3.12) and it worked on this data set.

Thanks for your help.
Rich Wolfe

________________________________

**Comment by ctSkennerton** [comment]
great!
