### ISSUE TITLE
Crass installation error

### ISSUE THREAD

**Issue by XiaoqiongGu** [ctSkennerton/crass#86]
Hi Skennerton,

When I try to compile the crass, some errors occur, here is the detail.

make  all-recursive
make[1]: Entering directory `/home/xiaoqiong/tools/crass'
Making all in src
make[2]: Entering directory`/home/xiaoqiong/tools/crass/src'
Making all in aho-corasick
make[3]: Entering directory `/home/xiaoqiong/tools/crass/src/aho-corasick'
make[3]: Nothing to be done for`all'.
make[3]: Leaving directory `/home/xiaoqiong/tools/crass/src/aho-corasick'
Making all in crass
make[3]: Entering directory`/home/xiaoqiong/tools/crass/src/crass'
/bin/bash ../../libtool  --tag=CXX   --mode=link g++ -I/usr/local/include -I/usr/local/include/xercesc -pedantic -Wall -g -O2 -L/usr/local/lib  -lz -lxerces-c   -o crass crass.o libcrass.a ../../src/aho-corasick/libacism.a 
libtool: link: g++ -I/usr/local/include -I/usr/local/include/xercesc -pedantic -Wall -g -O2 -o crass crass.o  -L/usr/local/lib -lz /usr/local/lib/libxerces-c.so libcrass.a ../../src/aho-corasick/libacism.a
libcrass.a(libcrispr.o): In function `findSingletons(char const*, options const&, std::vector<std::string, std::allocator<std::string> >*, std::map<std::string, bool, std::less<std::string>, std::allocator<std::pair<std::string const, bool> > >&, std::map<int, std::vector<ReadHolder*, std::allocator<ReadHolder*> >*, std::less<int>, std::allocator<std::pair<int const, std::vector<ReadHolder*, std::allocator<ReadHolder*> >*> > >*, StringCheck*, long&)':
/home/xiaoqiong/tools/crass/src/crass/libcrispr.cpp:509: undefined reference to`gzclose'
libcrass.a(libcrispr.o): In function `searchFile(char const*, options const&, std::map<int, std::vector<ReadHolder*, std::allocator<ReadHolder*> >*, std::less<int>, std::allocator<std::pair<int const, std::vector<ReadHolder*, std::allocator<ReadHolder*> >*> > >*, StringCheck*, std::map<std::string, bool, std::less<std::string>, std::allocator<std::pair<std::string const, bool> > >&, std::map<std::string, bool, std::less<std::string>, std::allocator<std::pair<std::string const, bool> > >&, long&)':
/home/xiaoqiong/tools/crass/src/crass/libcrispr.cpp:155: undefined reference to`gzclose'
/home/xiaoqiong/tools/crass/src/crass/libcrispr.cpp:144: undefined reference to `gzclose'
libcrass.a(SeqUtils.o): In function`getFileHandle(char const_)':
/home/xiaoqiong/tools/crass/src/crass/SeqUtils.cpp:105: undefined reference to `gzdopen'
/home/xiaoqiong/tools/crass/src/crass/SeqUtils.cpp:109: undefined reference to`gzopen'
libcrass.a(kseq.o): In function `ks_getc(kstream_t_)':
/home/xiaoqiong/tools/crass/src/crass/kseq.cpp:62: undefined reference to `gzread'
libcrass.a(kseq.o): In function`ks_getuntil(kstream_t_, int, kstring_t_, int_)':
/home/xiaoqiong/tools/crass/src/crass/kseq.cpp:87: undefined reference to `gzread'
collect2: error: ld returned 1 exit status
make[3]: *_\* [crass] Error 1
make[3]: Leaving directory `/home/xiaoqiong/tools/crass/src/crass'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory`/home/xiaoqiong/tools/crass/src'
make[1]: **\* [all-recursive] Error 1
make[1]: Leaving directory `/home/xiaoqiong/tools/crass'
make: **\* [all] Error 2

Can you help me look through it?
Thanks!

**Comment by ctSkennerton** [comment]
What operating system and version are you using?

**Comment by XiaoqiongGu** [comment]
Hi Skennerton,

My operating system is Ubuntu 14.04 LTS, x86_64 and my CRASS version is 1.0.1.

Thanks!

**Comment by ctSkennerton** [comment]
Can you download the latest commit and do a fresh installation, I think I've fixed the problem
