### ISSUE TITLE
Make error 

### ISSUE THREAD

**Issue by Ruonan0101** [ctSkennerton/crass#90]
Hi, 
There is some Make error at the end. At the source end of xerces, only 3.2.1 is found so I downloaded that. Can that be the potential cause of this? or something with WorkHorse.h? 
The attached is the log. 
make  all-recursive
make[1]: Entering directory `/mnt/home/wuruona1/CRASS_meta_CRISPR/crass'
Making all in src
make[2]: Entering directory `/mnt/home/wuruona1/CRASS_meta_CRISPR/crass/src'
Making all in aho-corasick
make[3]: Entering directory `/mnt/home/wuruona1/CRASS_meta_CRISPR/crass/src/aho-corasick'
/usr/bin/gcc -DHAVE_CONFIG_H -I. -I../..   -I/opt/software/zlib/1.2.11--GCC-4.4.5/include -I/opt/software/boost/1.47.0--GCC-4.4.5/include -I/opt/software/ClusterStudio/2013sp1/composer_xe_2013_sp1.0.080/mkl/include/fftw -I/opt/software/ClusterStudio/2013sp1/composer_xe_2013_sp1.0.080/mkl/include -I/opt/software/Python/2.7.2--GCC-4.4.5/include -I/opt/software/ClusterStudio/2011.0/composerxe-2011.5.220/tbb/include -I/opt/software/OpenMPI/1.4.3--GCC-4.4.5/include  -g -O2 -MT acism.o -MD -MP -MF .deps/acism.Tpo -c -o acism.o acism.c
mv -f .deps/acism.Tpo .deps/acism.Po
/usr/bin/gcc -DHAVE_CONFIG_H -I. -I../..   -I/opt/software/zlib/1.2.11--GCC-4.4.5/include -I/opt/software/boost/1.47.0--GCC-4.4.5/include -I/opt/software/ClusterStudio/2013sp1/composer_xe_2013_sp1.0.080/mkl/include/fftw -I/opt/software/ClusterStudio/2013sp1/composer_xe_2013_sp1.0.080/mkl/include -I/opt/software/Python/2.7.2--GCC-4.4.5/include -I/opt/software/ClusterStudio/2011.0/composerxe-2011.5.220/tbb/include -I/opt/software/OpenMPI/1.4.3--GCC-4.4.5/include  -g -O2 -MT acism_create.o -MD -MP -MF .deps/acism_create.Tpo -c -o acism_create.o acism_create.c
mv -f .deps/acism_create.Tpo .deps/acism_create.Po
/usr/bin/gcc -DHAVE_CONFIG_H -I. -I../..   -I/opt/software/zlib/1.2.11--GCC-4.4.5/include -I/opt/software/boost/1.47.0--GCC-4.4.5/include -I/opt/software/ClusterStudio/2013sp1/composer_xe_2013_sp1.0.080/mkl/include/fftw -I/opt/software/ClusterStudio/2013sp1/composer_xe_2013_sp1.0.080/mkl/include -I/opt/software/Python/2.7.2--GCC-4.4.5/include -I/opt/software/ClusterStudio/2011.0/composerxe-2011.5.220/tbb/include -I/opt/software/OpenMPI/1.4.3--GCC-4.4.5/include  -g -O2 -MT acism_dump.o -MD -MP -MF .deps/acism_dump.Tpo -c -o acism_dump.o acism_dump.c
mv -f .deps/acism_dump.Tpo .deps/acism_dump.Po
/usr/bin/gcc -DHAVE_CONFIG_H -I. -I../..   -I/opt/software/zlib/1.2.11--GCC-4.4.5/include -I/opt/software/boost/1.47.0--GCC-4.4.5/include -I/opt/software/ClusterStudio/2013sp1/composer_xe_2013_sp1.0.080/mkl/include/fftw -I/opt/software/ClusterStudio/2013sp1/composer_xe_2013_sp1.0.080/mkl/include -I/opt/software/Python/2.7.2--GCC-4.4.5/include -I/opt/software/ClusterStudio/2011.0/composerxe-2011.5.220/tbb/include -I/opt/software/OpenMPI/1.4.3--GCC-4.4.5/include  -g -O2 -MT acism_file.o -MD -MP -MF .deps/acism_file.Tpo -c -o acism_file.o acism_file.c
mv -f .deps/acism_file.Tpo .deps/acism_file.Po
/usr/bin/gcc -DHAVE_CONFIG_H -I. -I../..   -I/opt/software/zlib/1.2.11--GCC-4.4.5/include -I/opt/software/boost/1.47.0--GCC-4.4.5/include -I/opt/software/ClusterStudio/2013sp1/composer_xe_2013_sp1.0.080/mkl/include/fftw -I/opt/software/ClusterStudio/2013sp1/composer_xe_2013_sp1.0.080/mkl/include -I/opt/software/Python/2.7.2--GCC-4.4.5/include -I/opt/software/ClusterStudio/2011.0/composerxe-2011.5.220/tbb/include -I/opt/software/OpenMPI/1.4.3--GCC-4.4.5/include  -g -O2 -MT msutil.o -MD -MP -MF .deps/msutil.Tpo -c -o msutil.o msutil.c
mv -f .deps/msutil.Tpo .deps/msutil.Po
rm -f libacism.a
ar cru libacism.a acism.o acism_create.o acism_dump.o acism_file.o msutil.o 
ranlib libacism.a
make[3]: Leaving directory `/mnt/home/wuruona1/CRASS_meta_CRISPR/crass/src/aho-corasick'
Making all in crass
make[3]: Entering directory `/mnt/home/wuruona1/CRASS_meta_CRISPR/crass/src/crass'
/usr/bin/g++ -DHAVE_CONFIG_H -I. -I../..   -I/opt/software/zlib/1.2.11--GCC-4.4.5/include -I/opt/software/boost/1.47.0--GCC-4.4.5/include -I/opt/software/ClusterStudio/2013sp1/composer_xe_2013_sp1.0.080/mkl/include/fftw -I/opt/software/ClusterStudio/2013sp1/composer_xe_2013_sp1.0.080/mkl/include -I/opt/software/Python/2.7.2--GCC-4.4.5/include -I/opt/software/ClusterStudio/2011.0/composerxe-2011.5.220/tbb/include -I/opt/software/OpenMPI/1.4.3--GCC-4.4.5/include -I/usr/include -I/usr/include/xercesc -pedantic -Wall -g -O2 -MT PatternMatcher.o -MD -MP -MF .deps/PatternMatcher.Tpo -c -o PatternMatcher.o PatternMatcher.cpp
mv -f .deps/PatternMatcher.Tpo .deps/PatternMatcher.Po
/usr/bin/g++ -DHAVE_CONFIG_H -I. -I../..   -I/opt/software/zlib/1.2.11--GCC-4.4.5/include -I/opt/software/boost/1.47.0--GCC-4.4.5/include -I/opt/software/ClusterStudio/2013sp1/composer_xe_2013_sp1.0.080/mkl/include/fftw -I/opt/software/ClusterStudio/2013sp1/composer_xe_2013_sp1.0.080/mkl/include -I/opt/software/Python/2.7.2--GCC-4.4.5/include -I/opt/software/ClusterStudio/2011.0/composerxe-2011.5.220/tbb/include -I/opt/software/OpenMPI/1.4.3--GCC-4.4.5/include -I/usr/include -I/usr/include/xercesc -pedantic -Wall -g -O2 -MT Rainbow.o -MD -MP -MF .deps/Rainbow.Tpo -c -o Rainbow.o Rainbow.cpp
mv -f .deps/Rainbow.Tpo .deps/Rainbow.Po
/usr/bin/g++ -DHAVE_CONFIG_H -I. -I../..   -I/opt/software/zlib/1.2.11--GCC-4.4.5/include -I/opt/software/boost/1.47.0--GCC-4.4.5/include -I/opt/software/ClusterStudio/2013sp1/composer_xe_2013_sp1.0.080/mkl/include/fftw -I/opt/software/ClusterStudio/2013sp1/composer_xe_2013_sp1.0.080/mkl/include -I/opt/software/Python/2.7.2--GCC-4.4.5/include -I/opt/software/ClusterStudio/2011.0/composerxe-2011.5.220/tbb/include -I/opt/software/OpenMPI/1.4.3--GCC-4.4.5/include -I/usr/include -I/usr/include/xercesc -pedantic -Wall -g -O2 -MT LoggerSimp.o -MD -MP -MF .deps/LoggerSimp.Tpo -c -o LoggerSimp.o LoggerSimp.cpp
mv -f .deps/LoggerSimp.Tpo .deps/LoggerSimp.Po
/usr/bin/g++ -DHAVE_CONFIG_H -I. -I../..   -I/opt/software/zlib/1.2.11--GCC-4.4.5/include -I/opt/software/boost/1.47.0--GCC-4.4.5/include -I/opt/software/ClusterStudio/2013sp1/composer_xe_2013_sp1.0.080/mkl/include/fftw -I/opt/software/ClusterStudio/2013sp1/composer_xe_2013_sp1.0.080/mkl/include -I/opt/software/Python/2.7.2--GCC-4.4.5/include -I/opt/software/ClusterStudio/2011.0/composerxe-2011.5.220/tbb/include -I/opt/software/OpenMPI/1.4.3--GCC-4.4.5/include -I/usr/include -I/usr/include/xercesc -pedantic -Wall -g -O2 -MT SeqUtils.o -MD -MP -MF .deps/SeqUtils.Tpo -c -o SeqUtils.o SeqUtils.cpp
mv -f .deps/SeqUtils.Tpo .deps/SeqUtils.Po
/usr/bin/g++ -DHAVE_CONFIG_H -I. -I../..   -I/opt/software/zlib/1.2.11--GCC-4.4.5/include -I/opt/software/boost/1.47.0--GCC-4.4.5/include -I/opt/software/ClusterStudio/2013sp1/composer_xe_2013_sp1.0.080/mkl/include/fftw -I/opt/software/ClusterStudio/2013sp1/composer_xe_2013_sp1.0.080/mkl/include -I/opt/software/Python/2.7.2--GCC-4.4.5/include -I/opt/software/ClusterStudio/2011.0/composerxe-2011.5.220/tbb/include -I/opt/software/OpenMPI/1.4.3--GCC-4.4.5/include -I/usr/include -I/usr/include/xercesc -pedantic -Wall -g -O2 -MT CrisprNode.o -MD -MP -MF .deps/CrisprNode.Tpo -c -o CrisprNode.o CrisprNode.cpp
mv -f .deps/CrisprNode.Tpo .deps/CrisprNode.Po
/usr/bin/g++ -DHAVE_CONFIG_H -I. -I../..   -I/opt/software/zlib/1.2.11--GCC-4.4.5/include -I/opt/software/boost/1.47.0--GCC-4.4.5/include -I/opt/software/ClusterStudio/2013sp1/composer_xe_2013_sp1.0.080/mkl/include/fftw -I/opt/software/ClusterStudio/2013sp1/composer_xe_2013_sp1.0.080/mkl/include -I/opt/software/Python/2.7.2--GCC-4.4.5/include -I/opt/software/ClusterStudio/2011.0/composerxe-2011.5.220/tbb/include -I/opt/software/OpenMPI/1.4.3--GCC-4.4.5/include -I/usr/include -I/usr/include/xercesc -pedantic -Wall -g -O2 -MT NodeManager.o -MD -MP -MF .deps/NodeManager.Tpo -c -o NodeManager.o NodeManager.cpp
mv -f .deps/NodeManager.Tpo .deps/NodeManager.Po
/usr/bin/g++ -DHAVE_CONFIG_H -I. -I../..   -I/opt/software/zlib/1.2.11--GCC-4.4.5/include -I/opt/software/boost/1.47.0--GCC-4.4.5/include -I/opt/software/ClusterStudio/2013sp1/composer_xe_2013_sp1.0.080/mkl/include/fftw -I/opt/software/ClusterStudio/2013sp1/composer_xe_2013_sp1.0.080/mkl/include -I/opt/software/Python/2.7.2--GCC-4.4.5/include -I/opt/software/ClusterStudio/2011.0/composerxe-2011.5.220/tbb/include -I/opt/software/OpenMPI/1.4.3--GCC-4.4.5/include -I/usr/include -I/usr/include/xercesc -pedantic -Wall -g -O2 -MT libcrispr.o -MD -MP -MF .deps/libcrispr.Tpo -c -o libcrispr.o libcrispr.cpp
libcrispr.cpp: In function ‘unsigned int extendPreRepeat(ReadHolder&, int, int)’:
libcrispr.cpp:614: warning: comparison between signed and unsigned integer expressions
libcrispr.cpp:756: warning: comparison between signed and unsigned integer expressions
mv -f .deps/libcrispr.Tpo .deps/libcrispr.Po
/usr/bin/g++ -DHAVE_CONFIG_H -I. -I../..   -I/opt/software/zlib/1.2.11--GCC-4.4.5/include -I/opt/software/boost/1.47.0--GCC-4.4.5/include -I/opt/software/ClusterStudio/2013sp1/composer_xe_2013_sp1.0.080/mkl/include/fftw -I/opt/software/ClusterStudio/2013sp1/composer_xe_2013_sp1.0.080/mkl/include -I/opt/software/Python/2.7.2--GCC-4.4.5/include -I/opt/software/ClusterStudio/2011.0/composerxe-2011.5.220/tbb/include -I/opt/software/OpenMPI/1.4.3--GCC-4.4.5/include -I/usr/include -I/usr/include/xercesc -pedantic -Wall -g -O2 -MT WorkHorse.o -MD -MP -MF .deps/WorkHorse.Tpo -c -o WorkHorse.o WorkHorse.cpp
WorkHorse.cpp: In member function ‘bool WorkHorse::addDataToDOM(crispr::xml::writer*, xercesc_3_0::DOMElement*, int)’:
WorkHorse.cpp:2049: error: ‘class xercesc_3_0::DOMElement’ has no member named ‘getFirstElementChild’
WorkHorse.cpp:2052: error: ‘class xercesc_3_0::DOMElement’ has no member named ‘getFirstElementChild’
WorkHorse.cpp:2052: error: ‘class xercesc_3_0::DOMElement’ has no member named ‘getNextElementSibling’
make[3]: *** [WorkHorse.o] Error 1
make[3]: Leaving directory `/mnt/home/wuruona1/CRASS_meta_CRISPR/crass/src/crass'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/mnt/home/wuruona1/CRASS_meta_CRISPR/crass/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/mnt/home/wuruona1/CRASS_meta_CRISPR/crass'
make: *** [all] Error 2

**Comment by ctSkennerton** [comment]
I think this could be a version issue with xerces. Here is a link to the archive http://archive.apache.org/dist/xerces/c/3/sources/ Can you try with version 3.1.1

**Comment by ctSkennerton** [comment]
great
