### ISSUE TITLE
./autogen.sh gets hung up

### ISSUE THREAD

**Issue by dangeles** [ctSkennerton/crass#94]
Hi,

I tried to install CRASS on a Debian system, but `./autogen.sh` hangs up for >20min with absolutely no error report or verbose activity. Last command printed was `Automatically preparing build ... `. Any clue what might be going on?

Thanks!
David

**Comment by ctSkennerton** [comment]
That's a new one. Nope, I've got no idea what might be causing it. I think you could try running the steps manually by running the commands

```
libtoolize
aclocal -I m4
autoheader
automake --add-missing
autoconf 
```

or possibly just by using `autoreconf`

**Comment by dangeles** [comment]
Thanks for the suggestion! I left autopen running overnight, and it built, eventually. Super weird....
