### ISSUE TITLE
How to deal with paired-end Illumina reads

### ISSUE THREAD

**Issue by 473021677** [ctSkennerton/crass#97]
Hi:
   I am trying to use crass v0.3.6 to recover CRISPR spacer and repeat elements from metagenomic reads but I have encountered one problem. The metagenomic reads were generated by Illumina paired-end sequencing. So should I merge the two fastq files before I run crass? I will be eagerto get your guidance. Thanks very much.

Best regards,
YangYuan

**Comment by ctSkennerton** [comment]
Unfortunately crass doesn't use any of the read pair information however you don't need to merge the files. Crass can be given multiple files like `crass file_read1.fastq.gz file_read2.fastq.gz` and it will process both of them
