### ISSUE TITLE
Installation problem during make

### ISSUE THREAD

**Issue by schne236** [ctSkennerton/crass#98]
Hi,

I have searched through the other issues people have encountered, but while several were similar they didn't help me resolve this. 

System: I am running Ubuntu 20.04.1 LTS x86_64, under the Windows 10 - Windows Subsystem for Linux (WSL2, i.e. virtual machine with full linux kernel) (GNU/Linux 4.19.104-microsoft-standard x86_64). 
The gcc / g++ package is version 9.3.0
I just installed the newest versions of xerces and zlib, just a few days ago.

autogen.sh and configure run fine; I attached a text file with the "configure" onscreen output, and config.log file if that helps.
[configureOutput.txt](https://github.com/ctSkennerton/crass/files/5024326/configureOutput.txt)
[config.log](https://github.com/ctSkennerton/crass/files/5024396/config.log)

...but then when I run make the following happens:

`make  all-recursive`
`make[1]: Entering directory '/home/schne236/crass'`
`Making all in src`
`make[2]: Entering directory '/home/schne236/crass/src'`
`Making all in aho-corasick`
`make[3]: Entering directory '/home/schne236/crass/src/aho-corasick'`
`gcc -DHAVE_CONFIG_H -I. -I../..     -g -O2 -MT acism.o -MD -MP -MF .deps/acism.Tpo -c -o acism.o acism.c`
`mv -f .deps/acism.Tpo .deps/acism.Po`
`gcc -DHAVE_CONFIG_H -I. -I../..     -g -O2 -MT acism_create.o -MD -MP -MF .deps/acism_create.Tpo -c -o acism_create.o acism_create.c`
`mv -f .deps/acism_create.Tpo .deps/acism_create.Po`
`gcc -DHAVE_CONFIG_H -I. -I../..     -g -O2 -MT acism_dump.o -MD -MP -MF .deps/acism_dump.Tpo -c -o acism_dump.o acism_dump.c`
`mv -f .deps/acism_dump.Tpo .deps/acism_dump.Po`
`gcc -DHAVE_CONFIG_H -I. -I../..     -g -O2 -MT acism_file.o -MD -MP -MF .deps/acism_file.Tpo -c -o acism_file.o acism_file.c`
`mv -f .deps/acism_file.Tpo .deps/acism_file.Po`
`gcc -DHAVE_CONFIG_H -I. -I../..     -g -O2 -MT msutil.o -MD -MP -MF .deps/msutil.Tpo -c -o msutil.o msutil.c`
`mv -f .deps/msutil.Tpo .deps/msutil.Po`
`rm -f libacism.a`
`ar cru libacism.a acism.o acism_create.o acism_dump.o acism_file.o msutil.o`
`ar: 'u' modifier ignored since 'D' is the default (see 'U')`
`ranlib libacism.a`
`make[3]: Leaving directory '/home/schne236/crass/src/aho-corasick'`
`Making all in crass`
`make[3]: Entering directory '/home/schne236/crass/src/crass'`
`g++ -DHAVE_CONFIG_H -I. -I../..    -I/usr/local/include -I/usr/local/include/xercesc -pedantic -Wall -g -O2 -MT crass.o -MD -MP -MF .deps/crass.Tpo -c -o crass.o crass.cpp`
`mv -f .deps/crass.Tpo .deps/crass.Po`
********Here's where the error occurs:**
`/bin/bash ../../libtool  --tag=CXX   --mode=link g++ -I/usr/local/include -I/usr/local/include/xercesc -pedantic -Wall -g -O2 libcrass.a ../../src/aho-corasick/libacism.a -L/usr/local/lib  -lz -lxerces-c   -o crass crass.o`
`libtool: link: g++ -I/usr/local/include -I/usr/local/include/xercesc -pedantic -Wall -g -O2 -o crass crass.o  libcrass.a ../../src/aho-corasick/libacism.a -L/usr/local/lib -lz /usr/local/lib/libxerces-c.so`
`g++: error: libcrass.a: No such file or directory`
********Then it quits**
`make[3]: *** [Makefile:552: crass] Error 1`
`make[3]: Leaving directory '/home/schne236/crass/src/crass'`
`make[2]: *** [Makefile:372: all-recursive] Error 1`
`make[2]: Leaving directory '/home/schne236/crass/src'`
`make[1]: *** [Makefile:477: all-recursive] Error 1`
`make[1]: Leaving directory '/home/schne236/crass'`
`make: *** [Makefile:388: all] Error 2`

I've seen that others have had errors associated with the same couple lines of code, but none were because "libcrass.a" didn't exist. Any idea what's going on?

Thanks,
John

**Comment by ctSkennerton** [comment]
I'm not really sure why this is happening, but I was able to reproduce what you're seeing. As a workaround from the root of the git repo:

1. `./configure`
2. `cd src/crass && make libcrass.a` - build libcrass explicitly 
3. `cd ../../ && make` - go back to the root of the git repo and try making again

These steps worked for me, I hope they do for you too.

**Comment by schne236** [comment]
Thank you! It seems to have fixed it.

Though a couple warnings showed up while making libcrass.a; I don't know if these are important, I suppose I'll find out when I try to run it:

`g++ -DHAVE_CONFIG_H -I. -I../..    -I/usr/local/include -I/usr/local/include/xercesc -pedantic -Wall -g -O2 -MT libcrispr.o -MD -MP -MF .deps/libcrispr.Tpo -c -o libcrispr.o libcrispr.cpp`
`libcrispr.cpp: In function ‘unsigned int extendPreRepeat(ReadHolder&, int, int)’:`
`libcrispr.cpp:614:84: warning: comparison of integer expressions of different signedness: ‘unsigned int’ and ‘int’ [-Wsign-compare]`
`  614 |         if((last_repeat_start_index + searchWindowLength + right_extension_length) >= static_cast<int>(tmp_holder.getSeqLength())) {`
`      |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
`libcrispr.cpp:756:54: warning: comparison of integer expressions of different signedness: ‘unsigned int’ and ‘int’ [-Wsign-compare]`
`  756 |         if(*(repeat_iter+1) + right_extension_length >= tmp_holder.getSeqLength())`
`      |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~`
`SearchChecker.cpp:45:5: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]`
`   45 |     if (!SC_instance)`

And one during regular make:
`g++ -DHAVE_CONFIG_H -I. -I../..    -I/usr/local/include -I/usr/local/include/xercesc -pedantic -Wall -g -O2 -MT AssemblyWrapper.o -MD -MP -MF .deps/AssemblyWrapper.Tpo -c -o AssemblyWrapper.o AssemblyWrapper.cpp`
`AssemblyWrapper.cpp:235:16: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]`
`  235 |     std::cout<<"Usage: "PACKAGE_NAME<<"-assembler {--velvet|--cap3} -g INT -s LIST -x CRASS_XML_FILE -i INDIR [options]"<<std::endl;`
`      |                ^`
Maybe it fixes these automatically, I don't know. 
`      |     ^~`
`SearchChecker.cpp:47:9: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’`
`   47 |         return SC_instance;`
`      |         ^~~~~~`

**Comment by ctSkennerton** [comment]
Glad it worked. Generally warnings don't matter.

**Comment by schne236** [comment]
Thank you!
